"""Initial setup

Revision ID: 12ee96be11c3
Revises: 
Create Date: 2026-05-23 19:27:30.571523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ee96be11c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('pretty_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status_up', sa.Boolean(), nullable=True),
    sa.Column('last_change', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_address'), 'hosts', ['address'], unique=False)
    op.create_index(op.f('ix_hosts_id'), 'hosts', ['id'], unique=False)
    op.create_index(op.f('ix_hosts_user_id'), 'hosts', ['user_id'], unique=False)
    op.create_table('outages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('offline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('online_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outages_id'), 'outages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outages_id'), table_name='outages')
    op.drop_table('outages')
    op.drop_index(op.f('ix_hosts_user_id'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_id'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_address'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
