"""Add report settings

Revision ID: daf70869c087
Revises: f000f91c6d45
Create Date: 2026-06-07 02:27:49.672000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf70869c087'
down_revision: Union[str, None] = 'f000f91c6d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_settings', sa.Column('report_enabled', sa.Boolean(), nullable=True))
    op.add_column('chat_settings', sa.Column('report_time', sa.Time(), nullable=True))
    op.add_column('chat_settings', sa.Column('report_skip_empty_daily', sa.Boolean(), nullable=True))
    op.add_column('chat_settings', sa.Column('timezone_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_settings', 'timezone_name')
    op.drop_column('chat_settings', 'report_skip_empty_daily')
    op.drop_column('chat_settings', 'report_time')
    op.drop_column('chat_settings', 'report_enabled')
    # ### end Alembic commands ###
