"""Add ping_threshold and ChatSettings

Revision ID: f000f91c6d45
Revises: 12ee96be11c3
Create Date: 2026-06-07 01:18:16.938952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f000f91c6d45'
down_revision: Union[str, None] = '12ee96be11c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.add_column('hosts', sa.Column('ping_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'ping_threshold')
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
